spring:
  application:
    name: shopping-cart

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:6543/mydatabase}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8081}

logging:
  level:
    ru.yandex.practicum.commerce: TRACE
    org:
      springframework: ERROR