DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS addresses;

CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(70) NOT NULL,
    city VARCHAR(70) NOT NULL,
    street VARCHAR(200) NOT NULL,
    house VARCHAR(15) NOT NULL,
    flat VARCHAR(15),
    UNIQUE(country, city, street, house, flat)
);

CREATE TABLE IF NOT EXISTS delivery (
    delivery_id UUID PRIMARY KEY,
    from_address BIGINT NOT NULL REFERENCES addresses(id) ON DELETE RESTRICT,
    to_address BIGINT NOT NULL REFERENCES addresses(id) ON DELETE RESTRICT,
    order_id UUID NOT NULL,
    state VARCHAR(15) NOT NULL
);