spring:
  application:
    name: order

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:6543/mydatabase}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 0

logging:
  level:
    ru.yandex.practicum.commerce: TRACE
    org:
      springframework: ERROR

resilience4j:
  circuitbreaker:
    instances:
      shoppingCart:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s