DROP TABLE IF EXISTS shopping_cart_item;
DROP TABLE IF EXISTS shopping_cart;

CREATE TABLE IF NOT EXISTS shopping_cart (
    cart_id UUID PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    state VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS shopping_cart_item (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_cart_id UUID NOT NULL REFERENCES shopping_cart(cart_id) ON DELETE CASCADE,
    product_code UUID NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity >= 0)
);
