spring:
  application:
    name: collector

grpc:
  server:
    port: 59091
  client:
    analytics:
      address: ${GRPC_ANALYTICS_ADDRESS:static://localhost:9091}
      negotiationType: plaintext        # Отключение TLS для локальной отладки

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

collector:
  kafka:
    producer:
      properties:
        "bootstrap.servers": ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        sensor-events: ${KAFKA_TOPIC_SENSORS:telemetry.sensors.v1}
        hubs-events: ${KAFKA_TOPIC_HUBS:telemetry.hubs.v1}