spring:
  application:
    name: warehouse
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
    instance:
      preferIpAddress: true
      instanceId: ${spring.application.name}:${random.uuid}
